# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8654c035ef0a7326bbed98f388d95ccb1b9e3424a14a7c53c78cbcaa6a13e9c63d60ce2cb23d47315c517d564a0cf6e9f1f8e12c23742fff0653d0ebf86c339

test:
  secret_key_base: c48319fd6fdd72a58619bbb5f6475f8222612d98df59e13d4829c9fdafb6e715fdab58667525c5d805e21235217f4a63f091ab7403354a4bde12cac2a1123b38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
